In [1]:
import pandas as pd

In [2]:
# Create dataframe for Alabama

csv_path = "ALSerial.csv"
AL_serial_df = pd.read_csv(csv_path)
AL_serial_df.head()

,ID,Name,Alias,PrisonNum,PrisonState,KilrType,Sex,Race,WhiteMale,WhiteMale20s,...,OtherTotem,2020,BodyWater,BodySunk,YrsSent,DobbertPri,DobbertSec,PartnerID,KilrSubType,AttmpVics
0,11,"Akin, Joseph Dewey",NaN,NaN,NaN,Serial,1.0,1,1.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,Serial-Suspected,NaN
1,155,"Brown, Raymond Eugene",NaN,NaN,NaN,Serial,1.0,1,1.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,313,"Daughtrey, Earl Llewellyn, Jr.",NaN,NaN,NaN,Serial,1.0,1,1.0,1.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,Serial-Suspected,NaN
3,346,"Doss, Nancy Hazle","Doss, Nanny; Hazle Nancy; Hazel, Nancy",NaN,NaN,Serial,2.0,1,0.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,409,"Glover, Fred",NaN,NaN,NaN,Serial,1.0,2,0.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN