In [2]:
import pandas as pd

In [3]:
# Dataframe for Michigan

csv_path = "MIserial.csv"
MI_serial_df = pd.read_csv(csv_path)
MI_serial_df.head()

,ID,Name,Alias,PrisonNum,PrisonState,KilrType,Sex,Race,WhiteMale,WhiteMale20s,...,OtherTotem,2020,BodyWater,BodySunk,YrsSent,DobbertPri,DobbertSec,PartnerID,KilrSubType,AttmpVics
0,4,"Abuelazam, Elias","Eli, Elias Abullazam",842658,NaN,Serial,1.0,1.0,1.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,24,"Amos, Lowell Edwin",NaN,252661,NaN,Serial,1.0,1.0,1.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,Serial-Suspected,NaN
2,41,"Armstrong, John Eric",NaN,362407-2084912M,MI- Michigan Reformaory,Serial,1.0,1.0,1.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,6.0
3,47,"Atkins, Benjamin",NaN,237134,NaN,Serial,1.0,2.0,0.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,73,"Beck, Martha",NaN,NaN,NaN,Serial,2.0,1.0,0.0,0.0,...,0,0,0.0,0.0,NaN,NaN,NaN,402.0,NaN,NaN